### ISSUE TITLE
numba-scipy is now accepting PRs, discuss what to focus on first!

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba-scipy#10]
As title... place holder ticket for discussion over what to focus on first. `scipy.special` and `scipy.sparse` were suggested here: https://github.com/numba/numba/issues/4292#issuecomment-510257368

**Comment by luk-f-a** [comment]
I don't think I can help much with `scipy.special` (C integration is not my strong suit) but once `scipy.special` is available I will look into bringing in the statistical distributions

**Comment by Juanlu001** [comment]
I would love to see `scipy.integrate` :)

**Comment by person142** [comment]
I can do `scipy.special`. @Juanlu001 what parts of integrate are you most interested in seeing? Something like e.g. `quad` would be a royal pain, but if we’re talking e.g. Gaussian quadrature that’s much more approachable.

**Comment by person142** [comment]
(When it comes to adaptive quadrature it would probably be good to do some work on the SciPy side first vs. reproducing quadpack here.)

**Comment by stuartarchibald** [comment]
@person142 I agree, unless there's going to be some incredible performance (or other) benefit gained by translating core numerical libraries to Numba then creating a clean API on the callee side to make it easy for Numba make make the call is preferable.

**Comment by Juanlu001** [comment]
@person142 I was thinking more of accelerating the new Initial Value Problem solvers introduced in SciPy 1.0, which are much more feature-rich than `odeint` and `ode` but have a performance overhead because they're written in pure Python. I acknowledge though that it's not a trivial problem, but the question was open so... :innocent:

**Comment by stuartarchibald** [comment]
@person142 if you are happy to do `scipy.special` that'd be great, thanks. There's a tiny module in `numba-scipy` already for this, I was using it for CI and to get something uploaded to PyPI, feel free to wipe it with actual contents!

**Comment by person142** [comment]
> I was thinking more of accelerating the new Initial Value Problem solvers introduced in SciPy 1.0, which are much more feature-rich than odeint and ode but have a performance overhead because they're written in pure Python

Hm that is a quite interesting case. Could be that we should work on moving some stuff into Cython on the SciPy side to reduce overhead and then make sure it integrates well with Numba jitted functions...

**Comment by stuartarchibald** [comment]
@luk-f-a "Basic" support for `scipy.special` is added in the now merged https://github.com/numba/numba-scipy/pull/13 if you are interested in writing statistical distribution implementations? Thanks.

**Comment by luk-f-a** [comment]
thanks for letting me know @stuartarchibald . I started looking at it and I have a general question: should we aim to preserve the structure of the Scipy code? 

For example, for distributions I would need one auxiliary function from `scipy/_lib/_util.py`. Should I create a `numba-scipy/_lib/_util.py` file and put the jit-version in there?

**Comment by stuartarchibald** [comment]
@luk-f-a good point, perhaps we try with this approach and see how it goes ? There may be issues tracking upstream refactoring/places where it's just not reasonable to do this, however, it's probably worth a try as a predefined order might help.

**Comment by gioxc88** [comment]
Hello I am following the discussion with great interest and would like to ask how does it work exactly.
1. Do I need to import the package like `import numba-scipy`?
2. Does it work with scipy.stats? for example `scipyp.stats.chi2.rvs() scipy.stats.t.cdf() sp.stats.t.ppf()`
3. If not do you suggest any other method to speed up scipy functions (especially inversion of student t is very slow)
4. Where can I find information of how to help for integration between numba and scipy? I would like to contribute

many thanks

**Comment by luk-f-a** [comment]
hi @gioxc88 , it's great to hear that you're interested and even considering contributing. I started some work on `stats`, building `norm.rvs` as an example to test out the approach. But this has not been merged yet, so we're in a very early stage!! 

to your questions:

1. the idea is that you won't need to, Numba will recognize the calls to Scipy and call `numba-scipy` in the same way that it does with Numpy.
2. it will eventually, but which distribution works will depend on the community interest and contributions. There are 120 distributions in total, it will take some time. We're looking into how adding new distributions could be simplified.
3. Is your problem the time that `t.ppf` takes for each calculation, or that you might be calling it many times? 
4. Stay tuned on this issue for now, I assume that over time there'll be contributing guidelines. In particular, for `stats` I'd like to have a nice tutorial on adding new distributions.

ping @stuartarchibald

**Comment by gioxc88** [comment]
hello @luk-f-a 
thank you for your answer. I relied on the community for too long and now I think it's time for me to contribute.

I will certainly follow this issue.

About the `t.ppf` I need to call it in a loop 5 million times, for an a input array that has shape `[65, 13]`
This is because if I call it for a 3d array of shape `[65, 13, 5000000]` if won't fit my RAM.
But I tried with a 64Gb RAM pc to call it one single with the second 3d array time and it's still extremely slow compared do `t.cdf`. And whe I say extremely slow I am talking about `t.cdf` being executed in like 1 minutes while the `t.ppf` take more than 30 mins.

**Comment by luk-f-a** [comment]
>  I relied on the community for too long and now I think it's time for me to contribute.
same here!! :smile: 

I'm not surprised `ppf` is slower than `cdf`. I'm not sure about `t.ppf` in particular but it probably relies on numerical root finding of `cdf`. That means `cdf` might be run many times for each `ppf` call. The Scipy code seems to be in Cython (maybe we need a Scipy dev to confirm) so it's possible Numba might not improve performance. That array is pretty big (4bn numbers) anyway. For comparison, I ran the equivalent of `t.ppf` in Julia, and it took 1sec per million. That would mean 70 minutes for your big array. You might need a special algorithm (maybe gaussian quadrature?) if you really need to speed it up. Otherwise, create the numbers once, and read them from disk every time you need them.

**Comment by kkingstoun** [comment]
Hi, what about the Bessel functions, can I use it with numba?

**Comment by luk-f-a** [comment]
hi @kkingstoun , I did a quick test with `jv`and it worked.

```
from scipy import special as sp
import numba

@numba.njit
def test(v, z):
    return sp.jv(v, z)

print(sp.jv(3, 3), test(3., 3.))
```
There's a catch: it seems that you have to always pass the arguments as floats.

**Comment by kkingstoun** [comment]
Hi @luk-f-a, thank you for your response, but on my computer it doesn't work: 


```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'jv' of type Module(<module 'scipy.special' from '/home/kking/anaconda3/lib/python3.7/site-packages/scipy/special/__init__.py'>)

File "<ipython-input-332-f5add8b419a3>", line 6:
def test(v, z):
    return sp.jv(v, z)
    ^

[1] During: typing of get attribute at <ipython-input-332-f5add8b419a3> (6)

File "<ipython-input-332-f5add8b419a3>", line 6:
def test(v, z):
    return sp.jv(v, z)
    ^
```
Numba version: 0.45.1
Scipy: 1.3.0

**Comment by luk-f-a** [comment]
what happens if you run `from numba_scipy import special as nsp_sp`?

**Comment by kkingstoun** [comment]
@luk-f-a 

This line works, but:
```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-ce32addfc6b4> in <module>
      1 from numba_scipy import special as nsp_sp
----> 2 nsp_sp.jv(10)

AttributeError: module 'numba_scipy.special' has no attribute 'jv'


```

**Comment by luk-f-a** [comment]
do you have the latest numba-scipy master? Is `special` a .py file or a folder?

**Comment by kkingstoun** [comment]
@luk-f-a Yes, I see now, that there is a problem with installation. I dont'see the special directory, even after reinstallation using pip straight from the git. 

How should I install correctly?

**Comment by luk-f-a** [comment]
sorry, I don't know.

**Comment by stuartarchibald** [comment]
@kkingstoun please could you open an issue describing the problem you have? This issue is intended for discussion of features. Many thanks for your cooperation.

**Comment by stuartarchibald** [comment]
@luk-f-a @gioxc88 Great to hear you would like to contribute. I think the `stats` support is waiting on a transparent way to ship the e.g. `rv_continuous` class into compiled code, hope to get to this soon based on https://github.com/numba/numba-scipy/pull/16.

**Comment by hmc-cs-mdrissi** [comment]
My primary usage of scipy at the moment is the scipy.spatial.transform rotation stuff as I mostly work with computational geometry/computer vision code. Things like converting rotation matrix <-> quaternion <-> euler angles are my main scipy piece. It's not a high priority desire though just because the formulas to convert between them are simple enough to code directly and then let numba compile it.

Kd trees I've also considered using from scipy and would be helpful for low dimensional nearest neighbors problems.

**Comment by francoislauger** [comment]
When `stats` pull request will be integrated I will try to contribute. I'm working in a economic institut and we use Numba and scipy so this project is of great interest!

**Comment by stnatter** [comment]
1+ for `scipy.stats`. I am also using `scipy.interpolate` a fair bit and love to see that implemented.

**Comment by mberglundmx** [comment]
I would really like to see support for scipy.special.erf for complex values.

**Comment by remidebette** [comment]
Hi, thanks a lot for this awesome project.
I saw heavy performance improvements (while still being user readable) on code using scipy.stats by rewriting it to scipy.special functions.

But I agree with @Juanlu001 on the integrate functions. Currently, the bottleneck is in functions  such as quad which do not accept vectors and force the use of numpy.vectorize

Also, do you have docs on how the JIT compilation is done? including for FORTRAN routines?

**Comment by RobeeF** [comment]
Hi, I would also be very interested in scipy.interpolate !

**Comment by stuartarchibald** [comment]
The use of Numba's extension API `@overload` decorator is strongly recommended for providing JIT implementations of functions such as those found in SciPy. A guide to using `@overload` is [here](http://numba.pydata.org/numba-doc/dev/extending/overloading-guide.html?highlight=overload) and API documentation is [here](http://numba.pydata.org/numba-doc/latest/extending/high-level.html#implementing-functions).

It may be useful to take a look at examples of pull requests adding support for a NumPy function that have already been done if guidance is needed... here's a couple:

* `np.roll`: https://github.com/numba/numba/pull/3563/files
* `np.roots`: https://github.com/numba/numba/pull/2135/files

**Comment by rileymcdowell** [comment]
Chiming in with another vote for `scipy.stats` and the distributions contained therein.

Also, might be time to close https://github.com/numba/numba/issues/1707 and point it at this thread or a similar one.

FYI, if you decide to distribute the work, I would be interested in contributing the `scipy.stats.beta` and `scipy.stats.cauchy` distributions as those are what would do me the most good for me at the moment.

**Comment by luk-f-a** [comment]
hi @rileymcdowell , I've done some work to build the seed of `scipy.stats`, however my conclusions weren't all positive. I'll open an issue that discuss what I found with those interested, I'll ping you when I do.

**Comment by dlee992** [comment]
@luk-f-a , hi luk. Any new info about jitting `scipy.stats`? Recently, I met the usage of `stats.truncnorm` stuff, so want to know whether any news about it. And I am really wanting to contribute for this project, especially in `stats` module. But from ur past comments, things didn't go well?
