### ISSUE TITLE
jv special function not defined

### ISSUE THREAD

**Issue by PabloRdrRbl** [numba/numba-scipy#64]
We come from Issue #55.

I am using v0.0.3 and the following script.

```python
from numba import jit, njit, config, __version__, errors
from numba.extending import overload
import numba
import numpy as np

from scipy import special


@njit
def call_scipy_in_jitted_code():
    print("special.beta(1.2, 3.4)", special.beta(1.2, 3.4))
    print("special.jv(5.6, 1)       ", special.jv(5.6, 1))


call_scipy_in_jitted_code()
```

With the following error:

```
Traceback (most recent call last):
  File "D:\_\_\_\scratch.py", line 15, in <module>
    call_scipy_in_jitted_code()
  File "C:\anaconda3\envs\numba_scipy\lib\site-packages\numba\core\dispatcher.py", line 420, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\anaconda3\envs\numba_scipy\lib\site-packages\numba\core\dispatcher.py", line 361, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<ufunc 'jv'>) found for signature:

 >>> jv(float64, Literal[int](1))

There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload of function 'jv': File: numba_scipy\special\overloads.py: Line 9.
    With argument(s): '(float64, int64)':
   No match.

During: resolving callee type: Function(<ufunc 'jv'>)
During: typing of call at D:\_\_\_\scratch.py (12)


File "_\_\_.py", line 12:
def call_scipy_in_jitted_code():
    <source elided>
    print("special.beta(1.2, 3.4)", special.beta(1.2, 3.4))
    print("special.jv(5.6, 1)       ", special.jv(5.6, 1))
    ^
```

The code will work for `j0`, but not for `jv`.

**Comment by esc** [comment]
@PabloRdrRbl thank you for submitting this. I can confirm I am able to reproduce. Which is strange because the `jv` function 'should'  be available:

```
In [7]: from numba_scipy.special import signatures

In [8]: signatures.name_to_numba_signatures["jv"]
Out[8]: ((float64, float64),)
```

**Comment by esc** [comment]
@PabloRdrRbl I found the issue, you were passing in a Python integer instead of a float. If you change your example to use:

```
special.jv(5.6, 1.0)
```

Then it should work fine. Does that work for you too?

**Comment by esc** [comment]
Note: the error message also aludes to this, as it is looking for a signature: `With argument(s): '(float64, int64)':` -- but a `jv` with that signature is not available, only `(float64, float64)`.

**Comment by PabloRdrRbl** [comment]
It works! Thank you very much!

**Comment by esc** [comment]
@PabloRdrRbl ok, excellent! If you hit any other snags, please don't hesitate to reach out and thank you for using numba-scipy!

**Comment by PabloRdrRbl** [comment]
Thank you for the great support!
