### ISSUE TITLE
Add example

### ISSUE THREAD

**Issue by erwanp** [numba/numba-scipy#74]
Could you add an example of use in the Readme or in the Docs https://numba-scipy.readthedocs.io/en/latest/user/index.html , 
the user-manual is currently empty

**Comment by esc** [comment]
@erwanp thank you for submitting this. I have labeled it as a feature request. Pull-requests always welcome! 😇

**Comment by clarkedavida** [comment]
Please even a very simple example would be helpful! Can you maybe give a hint how to use this module? Does it come automatically with ` import numba`? The following code doesn't work, and I can't tell why.

```
from numba import jit
import scipy.special as sp


@jit(nopython=True)
def integral(a,b):
    sp.beta(a,b)
```

**Comment by esc** [comment]
> Please even a very simple example would be helpful! Can you maybe give a hint how to use this module? Does it come automatically with ` import numba`? The following code doesn't work, and I can't tell why.
> 
> ```
> from numba import jit
> import scipy.special as sp
> 
> 
> @jit(nopython=True)
> def integral(a,b):
>     sp.beta(a,b)
> ```

What error message do you get?

**Comment by clarkedavida** [comment]
```
>>> from numba import jit
>>> import scipy.special as sp
>>> @jit(nopython=True)
... def integral(a,b):
...     sp.beta(a,b)
... 
>>> integral(1,2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/.local/lib/python3.11/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/david/.local/lib/python3.11/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'beta' of type Module(<module 'scipy.special' from '/usr/lib/python3.11/site-packages/scipy/special/__init__.py'>)

File "<stdin>", line 3:
<source missing, REPL/exec in use?>

During: typing of get attribute at <stdin> (3)

File "<stdin>", line 3:
<source missing, REPL/exec in use?>
```

**Comment by clarkedavida** [comment]
OK you're correct, I somehow lost my numba-scipy installation... That's something I'll have to fix on my own.

Anyway do you think you could maybe give 1-2 short examples where numba-scipy works? I was originally interested in this to try to speed up double integrals of the form

``` scipy.integrate.quad( scipy.integrate.quad ( func, ... ) ) ```

My strategy so far has been to Numba as much of `func` as I can, but for my use-case there are a couple instances where it would be convenient to just numba-scipy a `scipy.integrate`.

Thanks for taking some time to look into this, I appreciate it.

**Comment by esc** [comment]
> OK you're correct, I somehow lost my numba-scipy installation... That's something I'll have to fix on my own.
> 
> Anyway do you think you could maybe give 1-2 short examples where numba-scipy works? I was originally interested in this to try to speed up double integrals of the form
> 
> `scipy.integrate.quad( scipy.integrate.quad ( func, ... ) )`
> 
> My strategy so far has been to Numba as much of `func` as I can, but for my use-case there are a couple instances where it would be convenient to just numba-scipy a `scipy.integrate`.
> 
> Thanks for taking some time to look into this, I appreciate it.
> 
> EDIT: Wait I'm just now noticing... Does numba-scipy actually work with the integrate module?

No, I don't think so. The currently supported functions are listed on: https://numba-scipy.readthedocs.io/en/latest/reference/index.html -- this is the scope of the scipy functions that can be used within a Numba `@njit` decorated context.
